### ISSUE TITLE
sandbox改成sandboxnew了

### ISSUE THREAD

**Issue by goofansu** [linjunpop/wechat_pay#1]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1

**Comment by linjunpop** [comment]
谢谢～我查看一下，之前没看到 issue 的通知。😳

**Comment by linjunpop** [comment]
哦，看了一下这个在 `0.2.0` 已经改好了，可以用 `WechatPay.API.get_sandbox_signkey/0` 来得到 signkey

**Comment by goofansu** [comment]
多谢，你这个项目写的真好，我正在学习中

**Comment by linjunpop** [comment]
@goofansu 过奖了，现在正在做一些修改，😳，然后也还没想清楚很好的方案让使用者可以自定义一些 http client 的行为。master 上现在已经改了一部分了

**Comment by goofansu** [comment]
@linjunpop 主要还是先用起来，我之前给别人做的项目还是用的ruby，因为有rails_admin，省了很多事，自己的项目慢慢在转到elixir来

**Comment by linjunpop** [comment]
边学边做 😄
