### ISSUE TITLE
In production, usually App, Native, Jsapi will has different config

### ISSUE THREAD

**Issue by j-deng** [linjunpop/wechat_pay#12]

**Comment by linjunpop** [comment]
For a workaround, you can try https://hexdocs.pm/wechat_pay/configuration.html#per-function-calls

**Comment by linjunpop** [comment]
Hi @j-deng I'm doing a refactor on the branch https://github.com/linjunpop/wechat_pay/tree/lose-weight

When it's ready, should resolve the issues you had met.
